# Generated by Django 4.2.10 on 2024-02-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_enquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
