# Generated by Django 4.2.10 on 2024-02-24 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0004_appointment_confirmed_appointment_rescheduled_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_wei", models.BigIntegerField()),
                ("amount_eth", models.DecimalField(decimal_places=8, max_digits=18)),
                ("transaction_hash", models.CharField(max_length=66)),
                ("sender_address", models.CharField(max_length=42)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("block_number", models.IntegerField(blank=True, null=True)),
                ("confirmation_count", models.IntegerField(blank=True, null=True)),
                (
                    "donor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
